### ISSUE TITLE
SimpleDataWindow.ValidateData returns inverted result

### ISSUE THREAD

**Issue by lipchev** [WildGums/Orchestra#104]
Hello,
this is a very simple issue- that was appears to have been discussed before on starckoverflow- but the issue is still there in the latest nuget (**version 5.1.5**), namely that the return should be negated in this method of SimpleDataWindow:

 protected virtual bool ValidateData()
    {
      IViewModel viewModel = this._logic.ViewModel;
      if (viewModel == null)
        return false;
      viewModel.Validate(false);
      return viewModel.ValidationContext.HasErrors;
    }

Best regards,
Galin LIPCHEV

**Comment by GeertvanHorrik** [comment]
Thanks, will fix this now.

**Comment by GeertvanHorrik** [comment]
Fixed, will be available in 5.1.6
