### ISSUE TITLE
Setting VerticalAlignment to "Stretch" does not affect buttons

### ISSUE THREAD

**Issue by ArXen42** [WildGums/Orchestra#121]
### Steps to reproduce

Replace the content of the `MainView` in `Orchestra.Examples.Ribbon.Fluent` with the following:

```xaml
<catel:UserControl x:Class="Orchestra.Examples.Ribbon.Views.MainView"
                   xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                   xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                   xmlns:catel="http://schemas.catelproject.com"
                   xmlns:orccontrols="http://schemas.wildgums.com/orc/controls">

    <orccontrols:StackGrid VerticalAlignment="Stretch">
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <Button Content="Test" VerticalAlignment="Stretch" />
        <TextBox Background="Gray" VerticalAlignment="Stretch" />
    </orccontrols:StackGrid>

</catel:UserControl>
```

Platform: WPF, Ribbon shell

### Expected behaviour

Button should be stretched vertically when corresponding vertical alignment is set.

### Actual behaviour

The `TextBox` will take bottom half of the screen (as expected), but the button won't be stretched vertically:
![image](https://user-images.githubusercontent.com/10744285/55408900-a0403400-5569-11e9-9fea-703abf975d10.png)

Breaking change was somewhere between versions 5.1.0-alpha0008 and 5.1.0-alpha0024. There were a lot of style changes during november, so I'm not sure which particular commit changed buttons.

If that was intentional, is there a way to override fixed height?

**Comment by GeertvanHorrik** [comment]
Sorry for the late reply, I totally missed this one. We will see if we can fix this in a hotfix.

**Comment by ArXen42** [comment]
Thanks!

**Comment by GeertvanHorrik** [comment]
I was hoping to fix this with a markup extension, but my attempt failed. For now, I think you can workaround this by setting the height to Double.NaN.

**Comment by ArXen42** [comment]
Oops, totally forgot to answer.
NaN solution seems to work fine, thanks!

And it turned out that dynamically stretching buttons is usually a bad UI decision anyway :)
Though still convenient for buttons with complex content.
