### ISSUE TITLE
Update Mahapps to v2.0 

### ISSUE THREAD

**Issue by bigworld12** [WildGums/Orchestra#186]
## Summary
Upgrade Mahapps.Metro package to V2.0 alpha

## API Changes
Mahapps.Metro v2.0 alpha brings some very interesting changes to the Theme experience, it also changes the way resource dictionaries are included in the project which makes it easier to swap themes and accents.
e.g.
https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.xaml#L10

https://github.com/punker76/code-samples#mahappsmetro-themes

it also adds some new functionality and controls to use.

these files for example can see a change
https://github.com/WildGums/Orchestra/blob/develop/src/Orchestra.Shell.MahApps/Themes/Controls.xaml

https://github.com/WildGums/Orchestra/blob/develop/src/Orchestra.Shell.MahApps/Helpers/MahAppsHelper.cs#L61
## Intended Use Case
It would make use of the new Mahapps.Metro functionality and make it easier to adapt new themes/styles

**Comment by GeertvanHorrik** [comment]
Btw interested in creating a PR for this? If not, please support us on [open collective](https://opencollective.com/wildgums-oss), then we will start working on this.

**Comment by bigworld12** [comment]
oh sure I would love to create a pr for this, but I am currently away so it might take some time.

p.s. I have been a supporter since day 1 on opencollective 😅

**Comment by GeertvanHorrik** [comment]
@bigworld12 oops, sorry, that's the difference between the GH names and the names on OC. We might need a way to somehow get this sorted out better.

Let me know if you need any help, otherwise we might look into this somewhere next week (but no promises yet, we have some internal deadlines to make).

**Comment by GeertvanHorrik** [comment]
Just checked, but it's still alpha?

**Comment by bigworld12** [comment]
yeah, but it's only the theming that needs to be changed

**Comment by GeertvanHorrik** [comment]
Yes, working on Fluent.Ribbon 7 update, it should use the same system.

**Comment by GeertvanHorrik** [comment]
See https://github.com/WildGums/Orchestra/issues/191

**Comment by GeertvanHorrik** [comment]
You can check out the special branch, it supports the new theming stuff from both Fluent.Ribbon and MahApps (2.x unstable).

**Comment by GeertvanHorrik** [comment]
Merged to develop. Still alpha, but hopefully they'll release a stable version soon.
