### ISSUE TITLE
Quick Start documentation needed

### ISSUE THREAD

**Issue by brian-pickens-web** [WildGums/Orchestra#194]
## Summary
I'm trying to get started using Orchestra with the ribbon.fluent shell. However I'm having a hard time getting started. I've tried taking a look at the example applications but that doesn't help me know where to start, and what things are key to setup. In particular, I've pulled in the nuget packages, and created a view from scratch... Now what? How do I pull in the various shells and start adding my own components to them?

## API Changes
This is a request for documentation

## Intended Use Case
Assistance in getting new users up to speed with a project from scratch

**Comment by GeertvanHorrik** [comment]
Thanks for reporting! Absolutely agree, unfortunately we don't have the resources to gets this up and running (and there isn't an advantage for us spending valuable resources on this). 

We have the examples apps (for each shell) that should give some hints on how to use the shell. I am happy to help you set up a shell with this, but are you willing to write the docs in return or consider backing us on open collective?

**Comment by GeertvanHorrik** [comment]
I've been working on project templates for both the Fluent.Ribbon and MahApps this evening. Seems to work great and should be pushed to the visual studio gallery any moment.

It's all open source, you can find more info here: https://github.com/catel/catel.templates

**Comment by GeertvanHorrik** [comment]
Also updated the readme of Orchestra:

https://github.com/wildgums/orchestra#project-templates
