### ISSUE TITLE
Suppressed error on creating mahapps shell window

### ISSUE THREAD

**Issue by bigworld12** [WildGums/Orchestra#205]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x] .NET Core

## Component
Orchestra.Shell.MahApps

## Version of Library
5.3.0-alpha0318

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. Simply running the sample app Orchestra.Examples.MahApps
2. Check Visual Studio's profiler, you can see multiple suppressed exceptions

## Expected Behavior
No exceptions

## Actual Behavior
multiple suppressed exceptions
e.g. :
> "Could not load file or assembly 'Catel.MVVM.Aero2, Version=5.11.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified." 

> "ImageSourceConverter cannot convert from (null)."

I am not sure if these should be a high priority thing, since it doesn't actually crash the app.
but just wanted to point them out

**Comment by GeertvanHorrik** [comment]
These are (already known) first chance exceptions. I don't think they can be prevented, but we will go through them in the next consolidation week.

**Comment by GeertvanHorrik** [comment]
The Catel.MVVM.Aero2 has been fixed (in latest Catel). Will look into the converter as well.

**Comment by GeertvanHorrik** [comment]
Fixed the other one as well, thanks for reporting!
