### ISSUE TITLE
Validation not fired when using Orchestra 

### ISSUE THREAD

**Issue by advapiIT** [WildGums/Orchestra#209]
I've created a demo project here https://github.com/advapiIT/OrchestraValidator to show the behavior 
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?

Every valiadtion component
## Version of OS(s) listed above with issue
Windows 10 64 bit

## Steps to Reproduce
1.Execut the OrchestraValidator
2.See the validation not showing
3.

## Expected Behavior
A red border around the textbox
The toolbar

## Actual Behavior
Nothing is shown

If you run the CatelValidationDemo that has the same code, you see the validation appearing

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/67939035-ff822780-fbd0-11e9-948c-35780126f08f.png)

**Comment by advapiIT** [comment]
I'm totally blocked by proxy... please find it here

https://drive.google.com/open?id=1J6G-d4BgAEn6UuDVQS3jf8m99Dghg1Go

Thanks

**Comment by advapiIT** [comment]
I've found that the current DeferValidationUntilFirstSaveCall is overridden.
I got the following log

11:07:33:136 => [DEBUG] [Catel.MVVM.ViewModelBase] [1] DeferValidationUntilFirstCall is 'False', but overriding value using parent view model value 'True'


Using 

```
  protected override async Task InitializeAsync()
        {
            await base.InitializeAsync();

            DeferValidationUntilFirstSaveCall = false;

        }
``` 
Does the trick. But doing so I've to specify that value in each VM on the InitializeAsync

HTH

**Comment by GeertvanHorrik** [comment]
Thanks for the investigation. I think it's because of the root shell view model (and the child vm's just follow the parent vm settings). Maybe we should make it configurable via the shell service.
