### ISSUE TITLE
add_ViewLoading Error

### ISSUE THREAD

**Issue by AnTri** [WildGums/Orchestra#23]
Hey, I tried the Ochestra Shell Template with VS2013. After setting up a new project and installing/update nuget packages (as readme file) I tried to start the application. 
While starting VS2013 reports the following error (sorry for german language):

> > Ein Ausnahmefehler (Exception) des Typs "System.TypeLoadException" ist in PresentationFramework.dll aufgetreten (occured).

Additional Informationen: Die Methode "add_ViewLoading" im Typ "Orchestra.Views.MainWindow" der Assembly "Orchestra.Shell, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.
<<

Thanks for helping me

AnTri

**Comment by EddieLa** [comment]
I had the same issue with the current prerelease of Orchestra and I'd just like to mention that the problem occurs if the target framework is .net 4.5  but doesn't occur in .net 4.0 so a quick fix is just not to target 4.5.

**Comment by GeertvanHorrik** [comment]
If you use 4.5, you must reference Microsoft.Bcl.Async. Did you do that? Can you provide a repro?

**Comment by EddieLa** [comment]
I had not referenced Microsoft.Bcl.Async, referencing it fixed the problem.
Thanks for the quick reply.
