### ISSUE TITLE
AdvancedLogViewerControl seems not to scroll to the end automatically...

### ISSUE THREAD

**Issue by Katsarakis** [WildGums/Orchestra#248]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
## Component
Orchestra

What component is this issue occurring in?
[assembly: AssemblyFileVersion("5.2.0")]
[assembly: AssemblyInformationalVersion("5.2.0-alpha.1")]

## Version of Library
latest... Catel 5.11.2

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1.  Start project Orchestra.Examples.TaskRunner
2.  klick Run...again and again. traceOutputControl is not scrolling to the end...
3.  in Orchestra with Catel 4.5.4 was working

## Expected Behavior
            <orclogviewer:AdvancedLogViewerControl x:Name="traceOutputControl"  />
traceOutputControl has to scroll automatically at the end

**Comment by GeertvanHorrik** [comment]
I think we have an open ticket for this internally, right @Averus-a ?

**Comment by Averus-a** [comment]
This is related to ORCOMP-450, will check this

**Comment by Katsarakis** [comment]
Hallo,
replaced 
<orclogviewer:AdvancedLogViewerControl x:Name="traceOutputControl"  />
by
<orccontrols:LogViewerControl x:Name="traceOutputControl" 
...it works!

**Comment by Katsarakis** [comment]
###                 <orc1:AdvancedLogViewerControl x:Name="traceOutputControl" 
                                                   AccentColorBrush="{orccontrols:ThemeColorBrush ThemeColorStyle=AccentColor}" 
                                                   ShowFilterBox="False" 
                                                   ShowFilterGroups="True" />
                

   
                    

Tabs (Error, Info, ...) are not visible  :-(

**Comment by Averus-a** [comment]
Hello.
These buttons are part of AdvancedLogViewerControl, whereas options like ShowError, ShowWarning etc. determine the display of log entries inside LogViewer from Orc.Controls. So there are two way: use LogViewerControl and create buttons yourself using these properties, or use the last alpha version of Orc.Controls (with fixes) with AdvancedLogViewerControl.

**Comment by Katsarakis** [comment]
https://opensource.wildgums.com/orc.logviewer/
Orc.LogViewer seems to be no supported anymore?

**Comment by GeertvanHorrik** [comment]
@Katsarakis not sure what you mean? We recently released a new version of the component and are actively fixing issues?

**Comment by Katsarakis** [comment]
the comment of @Averus-a is not suitable. reinvent the wheel:
"use LogViewerControl and create buttons yourself using these properties.."
The Orc.LogViewer is a fantastic control/component to use in an App as it has everything user neeeds.
The Error, Warning, Info, Debuf buttons and supports filtering. Clear and copy the output as well.
Is is a composition of Orc.Controls (LogViewerControl) with all functionallity noticed above.

**Comment by Averus-a** [comment]
@Katsarakis, agreed it is not suitable, but last versions should work fine.
Do you use Orc.LogViewer with last stable 3.3.0 or 3.4.0 alpha and is the same happened in Orc.LogViewer example? Default ScrollMode.ManualScrollPriority is default as it the same as old IsAutoScroll=true, "scroll automatically until something/somewhat scroll up back" behavior.

**Comment by Katsarakis** [comment]
@Averus-a , i have tested it with 3.4.0 the last alpha. 
Such a control like Orc.LogViewer i think it is better if its scrolls automaticaklly to the end every time a new entrie is logged inside the control.
The mode is changed to manually if user scrolls with mouse the context.
Try the sample inside in [](https://github.com/WildGums/LogViewer)

**Comment by GeertvanHorrik** [comment]
That the auto scroll stops when scrolling is by design. We could create a button to follow the tail again, but we should allow users to manually scroll

**Comment by Averus-a** [comment]
@GeertvanHorrik maybe provide ScrollMode option for Orc.LogViewer in a same way as in Orc.Control. Just pass it to the LogViewerControl. What do you think?

**Comment by GeertvanHorrik** [comment]
Agree. But... it should behave as:

1. Enabled by default
2. Disable as soon as the user manually scrolls
3. Have a checkbox / toggle button that can re-enable this
