### ISSUE TITLE
Orchestra.ProjectTemplates.Shell

### ISSUE THREAD

**Issue by AlexanderLiuckanov** [WildGums/Orchestra#26]
Hi,

some fix for this line in the template "Environment.RegisterDefaultViewModelServices();"

**Comment by EddieLa** [comment]
Are there any form of documentation or hints available for working with modules in orchestra?

**Comment by GeertvanHorrik** [comment]
Modules are not supported in Orchestra v2. If you want models, just hook in Catel.Extensions.Prism to use that module system. See the latest dev branch (examples folder) on how we put together the shell in v2.
