### ISSUE TITLE
Remove custom theme generation code for Fluent.Ribbon and MahApps.Metro

### ISSUE THREAD

**Issue by batzen** [WildGums/Orchestra#273]
## Summary
In the next major versions Fluent.Ribbon and MahApps.Metro will make use of a new shared ThemeManager from ControlzEx.
This new ThemeManager also contains the ability to generate themes at runtime.

The major versions are: 
- MahApps.Metro 2.0 which will be release in early may
- Fluent.Ribbon 8.0 which will be release in early to mid may

Thinking about this further you could, just maybe, replace your own theme handling with the one from ControlzEx.

## API Changes
The following classes should be removed:
- `FluentRibbonThemeHelper`
- `MahAppsThemeHelper`
The following nuget references should be removed:
- `XamlColorSchemeGenerator`

## Intended Use Case
Remove custom code used to generate themes for those two components and rely on the built-in theme generation.

**Comment by GeertvanHorrik** [comment]
Thanks for letting us know, we really appreciate this!

When will the next major versions be released? We are in the middle of shipping a new app based on the current fluent.ribbon which is breaking for us. If Fluent.Ribbon vNext is around the corner, we'd rather await that one. Then I will migrate all these things immediately as well.

**Comment by batzen** [comment]
MahApps 2.0 will be released in early may. Fluent.Ribbon will follow a few days later.
Not totally sure about the exact date, do you still plan may 1st @punker76?

**Comment by GeertvanHorrik** [comment]
Going to check whether I can already migrate the code base to the latest prereleases of MahApps and Fluent.Ribbon.

**Comment by GeertvanHorrik** [comment]
@batzen , have you considered creating markup extensions like these?

https://github.com/WildGums/Orc.Controls/tree/develop/src/Orc.Controls/Theming/Markup

I am considering to fully move to ControlzEx ThemeManager for both Orc.Controls and Orchestra. It would be great if there would be (updatable) MarkupExtensions available in ControlzEx as well. If not, I'll keep the markup extensions in Orc.Controls for now.

**Comment by batzen** [comment]
Will have a look at your suggestion this evening.
Please note that the thememanager changes are not in the fluent prerelease yet. This will also happen this evening. Do you need support for .net 4.5 or is .net 4.5.2 enough?

**Comment by GeertvanHorrik** [comment]
Awesome to hear! I am almost done stripping the theming code from Orc.Controls. The markup extensions now use a thin wrapper for the ThemeManager (keep current theme cached for performance). We don't need support for .net 4.5 I think. Our targets are now:

<TargetFrameworks>net46;net47;netcoreapp3.0;netcoreapp3.1</TargetFrameworks

**Comment by GeertvanHorrik** [comment]
Orc.Controls now uses ControlzEx for theming instead. I've kept a very thin layer just so I know what the selected theme is, but maybe I can even remove that in the future.

**Comment by GeertvanHorrik** [comment]
Pushed all changes for Orchestra.

**Comment by GeertvanHorrik** [comment]
Note that the ribbon is not yet responding to theme changes, but this is *probably* related to the fact that it doesn't use theming from ControlzEx yet.

**Comment by batzen** [comment]
Just published the first preview of 8.0 to nuget https://www.nuget.org/packages/Fluent.Ribbon/8.0.0-alpha0077

**Comment by GeertvanHorrik** [comment]
Great! Just updated and the ribbon now also respects the theme changes.

**Comment by GeertvanHorrik** [comment]
@batzen we are planning to start releasing the Orc controls suite. Do you have any schedule on when to release the v8 version of Fluent.Ribbon? We'd like to include that in our release.

**Comment by batzen** [comment]
Will try to get it done this week.

**Comment by batzen** [comment]
@GeertvanHorrik FYI: I discovered some bugs i introduced while fixing the logical tree and some other bugs in the automation peers.
As i got a lot of personal things to do this weekend (a birthday, bringing someone to Schiphol etc.) i am not sure if i can finish everything this week. I will try to, but i can't promise it.

**Comment by GeertvanHorrik** [comment]
Thanks for the headsup! Make sure to order your priorities right, and I think family / social > work / OSS, so enjoy your weekend! ;-)

**Comment by batzen** [comment]
@GeertvanHorrik Just published Fluent.Ribbon 8.0

**Comment by GeertvanHorrik** [comment]
Fantastic news, we will start releasing all our components today.
