### ISSUE TITLE
Third Party Notes

### ISSUE THREAD

**Issue by abrca** [WildGums/Orchestra#275]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] WPF
 - [X] .NET Standard

## Component

What component is this issue occurring in?
Orchestra.Core

## Version of Library
Fresh, from GitHub

## Version of OS(s) listed above with issue
Windows 10 x64

## Steps to Reproduce
1. Compile and run Orchestra.Examples.Ribbon.Fluent 
2. Press F1
3. In About window click "Third Party Notes" link

## Expected Behavior
Show all licenses

## Actual Behavior
Error with ControlzEx and Fluent.Ribbon licenses - [failed to load resources]

**Comment by GeertvanHorrik** [comment]
Great catch, thanks. Fixing...

**Comment by GeertvanHorrik** [comment]
Fixed, thanks for reporting!

**Comment by abrca** [comment]
And now Ricciolo is broken...

**Comment by GeertvanHorrik** [comment]
That should be removed, will remove it now.
