### ISSUE TITLE
Theme switching problem

### ISSUE THREAD

**Issue by abrca** [WildGums/Orchestra#277]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [x] .NET Standard
 - [x] .NET Core

## Component

What component is this issue occurring in?
Orchestra.Examples.MahApps 

## Version of Library
Fresh from GitHub

## Version of OS(s) listed above with issue
Windows 10 x64

## Steps to Reproduce
1. Compile and run Orchestra.Examples.MahApps 
2. Switch theme from Light to Dark

## Expected Behavior
Switching theme should affect whole UI

## Actual Behavior
![image](https://user-images.githubusercontent.com/20093250/81037761-4b35c680-8ebd-11ea-837b-0ff0016a8966.png)

(the same in Ribbon example)

**Comment by GeertvanHorrik** [comment]
I think this is because we need to add dark / light themes to the tab control. We are not at this stage yet, but are totally open for developers to add more styling.

**Comment by GeertvanHorrik** [comment]
Creating an Orc.Theming library that allows us to move faster with styling improvements without having to re-release both Orc.Controls and/or Orchestra.

**Comment by GeertvanHorrik** [comment]
Dark mode support is progressing nicely:

![image](https://user-images.githubusercontent.com/1246444/81140561-0e73d900-8f6a-11ea-893e-92a683cf3004.png)

**Comment by abrca** [comment]
verdeel en heers!

Concentrating code to Orc.Theming library gives the result

**Comment by GeertvanHorrik** [comment]
I am closing this issue, I think the theme switching issue is resolved and we will continue to improve the styling in our apps and components (but most is completed now).
