### ISSUE TITLE
Examples.Ribbon.Fluent indicator controls problem

### ISSUE THREAD

**Issue by abrca** [WildGums/Orchestra#280]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [x] .NET Standard

## Component

What component is this issue occurring in?
Orchestra.Examples.Shared\Views\ControlsView.xaml
(or, maybe Orc.Controls)

## Version of Library
Fresh from GitHub

## Version of OS(s) listed above with issue
Windows 10 x64

## Steps to Reproduce
1. Add checkpoints to Orchestra.Examples.Shared\Views\ControlsView.xaml:
![image](https://user-images.githubusercontent.com/20093250/81039574-e2514d00-8ec2-11ea-8527-12cd4f56cd18.png)

2. Compile and run Orchestra.Examples.Ribbon.Fluent 
3. Look on Orc controls group

## Expected Behavior
a) BusyIndicator control is visible
b) FluidProgressBar not to overlap neighbor labels (if it is not a feature)

## Actual Behavior
![image](https://user-images.githubusercontent.com/20093250/81039616-fe54ee80-8ec2-11ea-8c0c-2c66d2b7c27e.png)
![image](https://user-images.githubusercontent.com/20093250/81039628-044acf80-8ec3-11ea-8873-adcad13e4a22.png)

**Comment by GeertvanHorrik** [comment]
Good point, could be a negative margin. Will put it on the list to look at.

**Comment by GeertvanHorrik** [comment]
@Averus-a , can you fix this one?

**Comment by ceo1647** [comment]
the bug is actually in Orc.Controls... it now fixed in 4.0.1...waiting for package update

**Comment by ceo1647** [comment]
![image](https://user-images.githubusercontent.com/5163834/87978331-4c03ef00-cae1-11ea-8503-e8b1dfe3c0b1.png)

**Comment by ceo1647** [comment]
so it should be fixed in a latest develop
