### ISSUE TITLE
Microsoft.Ribbon UI doesn't show recently used items

### ISSUE THREAD

**Issue by auz34** [WildGums/Orchestra#29]
Orchestra.Examples.Ribbon.Microsoft project doesn't show recently used items even if viewmodel contains not empty RecentlyUsedItems list.

Steps to reproduce:
1. Go to auz34/Orchestra fork or accept pull request #28;
2. Start Orchestra.Example.Ribbon.Microsoft project.
3. Using open command open any file.
4. Close application and open it again

Expected Result:
Because RecentlyUsedItems array isn't empty ribbon should show at least one recently used item 

Actual Result:
Recently Used Items section is still empty
![image](https://cloud.githubusercontent.com/assets/3331375/5427009/c70a7d4e-8335-11e4-80fe-c46f84bc6220.png)

**Comment by GeertvanHorrik** [comment]
You have to explicitly set the data context in the menu for it to work.
