### ISSUE TITLE
IOrchestraService

### ISSUE THREAD

**Issue by jefjef** [WildGums/Orchestra#32]
In the documentation of orchestra it states you can use IOrchestraService to let your modules manipulate the shell ribbon, i realize the documentation is from an earlier version of Orchestra
and that the IOrchestraService no longer exists.

How would I do this in the newer version?

(i load the modules using prism)

**Comment by GeertvanHorrik** [comment]
Hi,

The repository of Orchestra contains a lot of examples for all shells (MahApps, Ribbon.Fluent, Ribbon.Microsoft). In the newest version, you are allowed to return the full ribbon. This means that you don't need to work with a complex API but can use the direct API of Fluent or Microsoft.

This is how you need to return the ribbon:

https://github.com/WildGums/Orchestra/blob/develop/src/Examples/Orchestra.Examples.Ribbon.Fluent/Orchestra.Examples.Ribbon.Fluent.Shared/Services/RibbonService.cs#L18

This is how you need to define the ribbon view:

https://github.com/WildGums/Orchestra/blob/develop/src/Examples/Orchestra.Examples.Ribbon.Fluent/Orchestra.Examples.Ribbon.Fluent.Shared/Views/RibbonView.xaml

**Comment by jefjef** [comment]
Ah so i can use the RibbonService in the modules and manipulate the RibbonView like that.

**Comment by GeertvanHorrik** [comment]
Exactly. This prevents us from having to maintain a shared ribbon API and you have all the freedom you want / need. This way Orchestra won't sit between you and the ribbon.

**Comment by GeertvanHorrik** [comment]
Closing this issue assuming it is solved for you. If not, feel free to re-open.
