### ISSUE TITLE
Catel.Extensions.Prism in Orchestra

### ISSUE THREAD

**Issue by jefjef** [WildGums/Orchestra#33]
i want to load some modules in my orchestra shell
i thought that this would be possible by adding Catel.Extensions.Prism to my shell application

But as soon as i do that my shell application stops working with an exception:
"Additional information: The type initializer for '<Module>' threw an exception."

I also don't really know how to use the Bootstrapper (for my modulecatalogs) too since Orchestra uses 
ApplicationInitializationService and Fody's ModuleInitializer

**Comment by GeertvanHorrik** [comment]
Can you upload a repro? It can be tons of things.

**Comment by jefjef** [comment]
Sure, ill create an example and upload that when finished

**Comment by jefjef** [comment]
I managed to get past the first error by reinstalling all nuget packages, must have had a wrong version somewhere

Now i get the following error: "Additional information: ServiceLocationProvider must be set."
(I think it has got something to do with the prism region in the MainView)

See the example repo at https://github.com/jefjef/OrchestraPrismIssue

**Comment by jefjef** [comment]
Do i need to use the ModuleInit.Fody in these projects, i see all the examples use it,
or can i just use the bootstrapper from Catel.Extentions.Prism?

**Comment by GeertvanHorrik** [comment]
I don't do a lot with prism. You will need to use the Catel Prism bootstrapper instead of manually setting things up. See the Catel.Examples repository on how to set it up:

https://github.com/Catel/Catel.Examples/blob/master/src/NET/Catel.Examples.WPF.Prism/Bootstrapper.cs

**Comment by jefjef** [comment]
I removed ModuleInit.Fody and used the Bootstrapper instead and everything seems to be working now.

The only problem i have now is this in the bootstrapper:

```C#
protected override DependencyObject CreateShell()
{
    LogManager.AddDebugListener(true);

    var serviceLocator = ServiceLocator.Default;
    var shellService = serviceLocator.ResolveType<IShellService>();
    shellService.CreateWithSplash<ShellWindow>();
    return null;
}
```

The CreateWithSplash methode returns an async task,
when i wait for the result to return it everything gets locked (indefinitely)
(so for now i just return null, which seems to be working, the shell starts)

You may close the issue i think i can continue from here

**Comment by GeertvanHorrik** [comment]
Prism isn't really ready for async / await (at least the bootstrapper). You can create the shell yourself and show the splash screen yourself in different locations of the bootstrapper. Basically the "bootstrapper" inside Orchestra is a light-weight version of the Prism bootstrapper.
