### ISSUE TITLE
Visual Studio 2015 templates

### ISSUE THREAD

**Issue by SkyQuant** [WildGums/Orchestra#35]
Are VS2015 templates available? I can't find it in Extension manager searching with _Orchestra_ keyword.

**Comment by GeertvanHorrik** [comment]
Not yet. Our resources are limited unfortunately.

**Comment by pascalgross** [comment]
Sorry for hijacking, but I thinks it's related:
The documentation states 'Note that project templates are available and this guide assumes that they are installed on the machine' - But where? I can't find those templates, neither for manual download nor in the online template library. VS 2013 and 2015.

**Comment by GeertvanHorrik** [comment]
What documentation?

**Comment by pascalgross** [comment]
https://github.com/WildGums/Orchestra/blob/develop/doc/getting%20started/GettingStarted.md

**Comment by GeertvanHorrik** [comment]
That guide is really outdated, I wasn't even aware of it. Just check out the examples for now, they are the best we have atm.

**Comment by pascalgross** [comment]
Okay, thanks.

**Comment by GeertvanHorrik** [comment]
We have decided we are not going to create VS templates for this. If we are going to create templates, we will use the Solution Generator (https://github.com/wildgums/solutiongenerator) for this.

**Comment by RainerBohrmann** [comment]
This is kinda disappointing after weeks of waiting for the templates to come.
Maybe someone can provide a simple step by step guide how to do it manually from the scatch
like this
1. create a new CATEL WPF project
2. get the Orchestra.Shell.Ribbon.Fluent from nuget
.....
start your application

**Comment by GeertvanHorrik** [comment]
I can understand your frustration, but it's all a matter of resources and where we should focus on. We maintain over 30 libraries, we can't please everyone. But since it's all open source, feel free to contribute!

**Comment by RainerBohrmann** [comment]
Hey Geert,
i really understand the problem with limited resources but whats the point in providing all these libraries to the people but not telling them how to use it?
The "Getting Started" Document ist outdated, VS Templates are not coming soon.
There is no other baisc Information availible.
My resouces are limited too. So how can i make some progress and start contributing to the project?

**Comment by GeertvanHorrik** [comment]
Hi Rainer,

_This comment is really not meant to be rude, but I want to be very clear on our goals, our (limited) resources and why components are being put online._

> whats the point in providing all these libraries to the people but not telling them how to use it?

We are not a charity organization. We do provide everything we feel can be useful to others on the internet for free so they can be used by others, but our core business is not to provide free to use components for others. **Most components we use are provided with examples** (yes, Orchestra as well, it has examples for each shell type). The point is that a lot of people find the libraries very useful, but again, it's not our primary goal to provide free components to you. It's something we give to the community, it's up to the community to decide whether they want to use this stuff (again, for free).

> The "Getting Started" Document ist outdated, VS Templates are not coming soon.

Correct, I will delete that.

> There is no other baisc Information availible.

Don't agree, this repository contains examples for each shell.

> My resouces are limited too. So how can i make some progress and start contributing to the project?

Clone the repository, check out the examples. You can even copy/paste the whole example projects and you will be up and running within a few minutes.

**Comment by askdong** [comment]
Frankly speaking, Catel is a wonderful framework and my project benefit a lot from it.
I think Catel examples and Orchestra give enough information to us to study it, just be patient and spend your time on examples and you will understand how it works.  step by step guides and templates is not necessary for good self-taught programmer!

**Comment by GeertvanHorrik** [comment]
I can totally understand the request, we just don't have the resources to fulfill it. We are not Microsoft with unlimited budgets to create tools / documentation / etc. Besides all the components we put available for free, we actually need to make products that bring in money :-)
