### ISSUE TITLE
Orchestra.Shell.Ribbon.Microsoft doesnt have strong name

### ISSUE THREAD

**Issue by auz34** [WildGums/Orchestra#38]
![image](https://cloud.githubusercontent.com/assets/3331375/9971818/abc874f0-5e13-11e5-9c17-4291a944f593.png)

**Comment by GeertvanHorrik** [comment]
We don't sign our libraries. There are tons of pros and cons, so we decided not to sign. This way everyone can decide whether they want to sign it themselves (for example, as a pre-build step).
