### ISSUE TITLE
Add support for Material Design In Xaml Toolkit

### ISSUE THREAD

**Issue by Mazzelfassel** [WildGums/Orchestra#382]
## Summary
Add a way to apply the MaterialDesignInXamlToolkit onto the MahApps.Metro shell. The result would be, that the Style of Metro would be overridden by the MaterialDesign whereas the window style would remain.

## API Changes
Add a functionality to exchange/overwrite the existing Metro Style with the MaterialDesign Style. Because MaterialDesignInXamlToolkit already supports the be used in combination with MahApps.Metro most of the changes chould be adapted from their implementation. 
The current method to apply the MaterialDesign in combination with MahApps.Metro looks like this:

```xaml
<ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml"/>
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml"/>

        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml"/>

        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Defaults.xaml"/>

        <materialDesignMahApps:MahAppsCustomColorTheme BaseTheme="Dark" PrimaryColor="Orange" SecondaryColor="Gray" />
        
    </ResourceDictionary.MergedDictionaries>
```

This code would be inserted into the ```App.xaml``` but in the current case it won't work because the style is overwritten at a later point. Applying the same code directly on a component/window level partially works but still shows some problems with layouting.
## Intended Use Case
The feature could be used by anyone who intends to use the MaterialDesign Style of the MaterialDesignInXamlToolkit in combination with the MVVM-Model of Catel.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. Should be a fairly easy fix. We'll plan this for Orchestra 6.1, but I expect to deliver a first alpha soonish.

**Comment by GeertvanHorrik** [comment]
Considering whether we should use Orc.Theming for this or Orchestra.

**Comment by GeertvanHorrik** [comment]
Introducing this interface in Orchestra:

```
public interface IXamlResourceService
{
    IEnumerable<ResourceDictionary> GetApplicationResourceDictionaries();
}
```

The default implementation will mimic current behavior, but can be adjusted to add multiple resource dictionaries. Will update the examle to show the material design toolkit.

**Comment by GeertvanHorrik** [comment]
Example implementation:

```
public override IEnumerable<ResourceDictionary> GetApplicationResourceDictionaries()
{
    // This example shows a fully customized resource dictionary being loaded by
    // the XamlResourceService. See https://github.com/WildGums/Orchestra/issues/382S

    // In order to use a fully customized xaml resource dictionary, we will remove the 
    // default orchestra one for the shell 

    var items = new List<ResourceDictionary>(base.GetApplicationResourceDictionaries());

    var shellResourceDictionaries = (from item in items
                                        where item.Source?.ToString().Contains("Orchestra.Shell.MahApps") ?? false
                                        select item).ToList();

    foreach (var shellResourceDictionary in shellResourceDictionaries)
    {
        items.Remove(shellResourceDictionary);
    }

    return items;
}
```

**Comment by GeertvanHorrik** [comment]
It maybe require a bit of tweaking, but it's applying the material design style:

![image](https://user-images.githubusercontent.com/1246444/89761706-4ea9a100-daef-11ea-9fdc-a0816585aab9.png)

**Comment by GeertvanHorrik** [comment]
Releasing alpha version of Orchestra 6.1 with this new feature. Please check the example, it shows how to customize what resource dictionaries are being loaded.

The example itself defines the MaterialDesigns as separate resource dictionary so it's easy to switch between on and off (comment 2 lines of code in ModuleInit), but in your app you can simply put them in your app.xaml now.
