### ISSUE TITLE
IPleaseWaitService resolved as PleaseWaitService instead of ProgressPleaseWaitService 

### ISSUE THREAD

**Issue by ttustonic** [WildGums/Orchestra#384]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x] .NET Core

## Component

Orchestra.Shell.Ribbon.Fluent

## Version of Library
6.0.2

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1.Create a new Fluent application using Fluent.Ribbon project wizard. It uses Catel ver. 5.11.2 and Orchestra shell ver. 5.3.0.-alpha0296
2. Add following line somewhere (for example in the constructor of `MainViewModel`):
            `var pleaseWait = ServiceLocator.Default.ResolveType<IPleaseWaitService>();`
 when stopped in debugger, it is correctly resolved as `Orchestra.Services.ProgressPleaseWaitService.`
3. Update Nuget packages:  Catel -> 5.12.7, Orchestra.Shell.Ribbon.Fluent -> 6.0.2, Fody -> 6.2.4
4. Update target frameworks to .Net core 3.1 and .Net framework 4.7.2 
5. Run again

## Expected Behavior
The `pleaseWait `variable should be resolved as `Orchestra.Services.ProgressPleaseWaitService.` 

## Actual Behavior
It is resolved as `Orchestra.Service.PleaseWaitService.` ProgressPleaseWaitService is registered in Shared `ModuleInitializer.cs`, but it seems that it's not included in any of the Orchestra.Shell.* projects

**Comment by ttustonic** [comment]
It needs `LoadAssembliesOnStartup.Fody `.
Perhaps it should be documented somehow.
Anyway, I'll close the issue.

**Comment by GeertvanHorrik** [comment]
Technically you don't need LoadAssembliesOnStartup. But this is exactly why it was created. If you are only using *interfaces* from an assembly, that assembly is not loaded into an app domain. You need to use explicit types from an assembly to load an assembly into the app domain (which is what LoadAssembliesOnStartup is doing for you).

**Comment by ttustonic** [comment]
Well, yes, I understand what LoadAssembliesOnStartup does. But, without it, IPleaseWaitService resolves to the one from Orchestra.Core instead the ProgressPleaseWaitService from the Shared project.
I just tried with the Fluent Ribbon Example -- when I remove LoadAssembliesOnStartup from FodyWeavers, the progress bar is not shown in LongOperation demo.

**Comment by GeertvanHorrik** [comment]
Correct, because no actual types from the shell are being used. So, no reason for the runtime to load the assembly into the app domain. Thus not giving the assembly a chance to register new implementations.
