### ISSUE TITLE
Catel has moved to Github. URL for your Readme.md

### ISSUE THREAD

**Issue by CADbloke** [WildGums/Orchestra#40]
Hiya

Firstly, nice work on all these repos here. Thanks for posting them, and to Nuget.

Easy one - Catel has moved to http://catelproject.com/  and posted their repo at https://github.com/catel/catel

Your readme still points to the Codeplex sites. 

Cheers
Ewen

**Comment by Orcomp** [comment]
Thanks Ewen. The links have been fixed.
