### ISSUE TITLE
ShouldCreateStyleForwarders=true disables the BackgroundToForegroundConverter behavior (MahApps)

### ISSUE THREAD

**Issue by lipchev** [WildGums/Orchestra#406]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x] .NET Core

## Component

Orchestra.Examples.MahApps

## Version of Library

Orc.Theming (4.0.2), Orchestra.Shell.MahApps (6.0.4)

## Version of OS(s) listed above with issue

Win 10, .net core 3.1

## Steps to Reproduce
1. Open the MahApps.Shell example from the Orchestra package
2. Select a dark accent color (keeping the light theme): say '#FF000000' (black)

## Expected Behavior

The text elements on all HeaderedControls (GroupBox, Expander, TitleBar) should switch from black to white color brush 

## Actual Behavior
![image](https://user-images.githubusercontent.com/5253184/92530365-ed333a00-f234-11ea-9e74-ac5b41d8f849.png)

I'm quite stunned by this- as it would appear that the DefaultStyles from MahApps/Themes/Controls.xaml are being set as default (e.g. DefaultGroupBoxStyle- which, as you know, is [`BasedOn="{StaticResource MahApps.Styles.GroupBox}"`](https://github.com/WildGums/Orchestra/blob/c792abd3f48f8696e9a4249e604aa89dcd706c8a/src/Orchestra.Shell.MahApps/Themes/Controls.xaml#L42))- yet the TextElement.Foreground never seems to change. I've also tried styling one of the GroupBoxes with [`"{DynamicResource MahApps.Styles.GroupBox}"`](https://github.com/MahApps/MahApps.Metro/blob/c36f14da09ff70630d9e558a6f4564c34c176e9e/src/MahApps.Metro/Styles/Controls.GroupBox.xaml#L11) and still no difference.

**Finally - disabling the StyleForwarding (ShouldCreateStyleForwarders = false) produces the expected result** 

![image](https://user-images.githubusercontent.com/5253184/92531785-a5fa7880-f237-11ea-97a0-11be9d158ce7.png)

**Comment by GeertvanHorrik** [comment]
The style forwarders indeed create default textblock styles. @ceo1647 , how do we want to deal with such specific scenarios? I  am tempted not to support it for now since we won't be using dark colors and we need to differentiate between dark headers (white text) and light background (black text).

**Comment by lipchev** [comment]
My choice of color in this example is extreme- but even using the MahApps standard blue theme causes the color-inversion. You might argue this is a matter of taste/preference- but this is also causing a lot of issues with migrating my existing application- with some headers turning black while others (containing buttons/custom controls) - remaining white (as manually set to IdealForegroundColorBrush).

**Comment by GeertvanHorrik** [comment]
@ceo1647 has optimized the TabControl headers. Maybe this also fixes the group box headers?

**Comment by lipchev** [comment]
I quite like the TabItem style (with the remark that HeaderedControlHelper.HeaderFontSize is not taken into account). Unfortunately I've run into other color inversion problems- for example both MahApps.Styles.DataGrid & AzureDataGrid used to inverse the color of the text elements inside a cell template (for the selected row). And now- with the StyleForwarding option on I get this:

![image](https://user-images.githubusercontent.com/5253184/96304447-cb339100-1004-11eb-9868-754b0d416f3d.png)

**Comment by GeertvanHorrik** [comment]
@lipchev can you post an image without style forwarders as well?

@ceo1647 can you look into this?

**Comment by lipchev** [comment]
Couldn't find the exact color- but it's the same for any one. Note that these are from the (latest) master branch (the dev branch is whole new game). Also note that [#118](https://github.com/WildGums/Orc.Theming/issues/118) is still valid.
![image](https://user-images.githubusercontent.com/5253184/96309038-2b2e3580-100d-11eb-909f-d07cf3eecbb8.png)
