### ISSUE TITLE
AccentColorBrush - inconsistency

### ISSUE THREAD

**Issue by Allann** [WildGums/Orchestra#41]
Hi, was just looking through the examples and noticed that in the MahApps example the AccentColorBrush is not used when it gets to the actual app, just the splash screen.  I have not looked into the issue much though.  If this is by design, how would I change the App color?

**Comment by GeertvanHorrik** [comment]
Hi @Allann , it's a bit dynamic. You only have to define the AccentColorBrush (from the top of my head, the examples surely work) in the main application resources dictionary. Then the Orchestra shell will create a dynamic MahApps resource dictionary with all the correct accent colors.

In the example app, you can change it here:

https://github.com/WildGums/Orchestra/blob/develop/src/Examples/Orchestra.Examples.MahApps/Orchestra.Examples.MahApps.Shared/Themes/Generic.xaml#L4

**Comment by PatrickTenHove** [comment]
Can this also be applied to the flyout control theme. Because the theme for this is now set fixed to Adapt. But I like to set it to Inverse instead.

**Comment by GeertvanHorrik** [comment]
I don't think that is possible out of the box.

**Comment by PatrickTenHove** [comment]
Can we not just add a extra parameter to the AddFlyout method of the FlyoutService and to the extension method? With a default value set to Adapt?

**Comment by Allann** [comment]
Ah thanks, I was a few checkins behind.  Must have fixed it recently as the latest sync fixed it.

**Comment by GeertvanHorrik** [comment]
@PatrickTenHove please create a new issue so we can discuss it there.
