### ISSUE TITLE
The theme of the Flyout window is not adjustable

### ISSUE THREAD

**Issue by PatrickTenHove** [WildGums/Orchestra#42]
Can we not just add a extra parameter to the AddFlyout method of the FlyoutService and the FlyoutServiceExtension? With a default value set to Adapt? So you can set the theme of the fly out window if you want to use u different theme for your flyout windows.

**Comment by GeertvanHorrik** [comment]
I need to think about it. If we are calling this from withing a VM, it might sound a bit weird to set the theming there. But will look into it (maybe we can default to a specific value not to bother everyone with it).

**Comment by GeertvanHorrik** [comment]
Implementing it without trying to cause breaking changes.

**Comment by GeertvanHorrik** [comment]
Seems to work!

**Comment by GeertvanHorrik** [comment]
Build - 2.4.0-unstable.5 being released right now.

**Comment by PatrickTenHove** [comment]
Just like as I suggested it @GeertvanHorrik thanks!
