### ISSUE TITLE
Taskbar icon not visible while SplashScreen

### ISSUE THREAD

**Issue by tbitowt** [WildGums/Orchestra#43]
Is it possible to show TaskBar icon while loading application?

I have following code in my `App.xaml.cs OnStartup()` method:

            var serviceLocator = ServiceLocator.Default;
            var shellService = serviceLocator.ResolveType<IShellService>();
            try
            {
                shellService.CreateWithSplash<OrtManWindow>();
            }
            catch
            {
                // ignored
            }

The problem is that this initialization least for about ~10s for my application and during that I'm checking some requirements. If some of them are not met, I'm showing kind of messagebox. If it appears, my SplashScreen could be under all windows and nobody even know, that the error is shown.

So it would be great to show taskbar icon on beginning of initializing application

**Comment by GeertvanHorrik** [comment]
We have considered this, but aren't sure whether we should do it or not. If you can do a PR, we will accept it ;-)

Maybe an additional Method / Property on the IShellService called *ShowSplashInTaskBar* so users can customize this any time.

**Comment by GeertvanHorrik** [comment]
Btw did you try the latest prerelease? Just checked and it already shows the icon during the splash screen.

**Comment by GeertvanHorrik** [comment]
@tbitowt Is this issue still relevant?

**Comment by tbitowt** [comment]
It's working on latest pre-release. Thanks
