### ISSUE TITLE
Shortcut manager - CommandInfoService command cache leads to erroneous data presented to user in KeyboardMappingsCustomizationView

### ISSUE THREAD

**Issue by greg9504** [WildGums/Orchestra#46]
To reproduce:
Run sample
Select the Keyboard Shortcuts icon
This displays the KeyboardMappingsCustomizationView view
Select the Help About short cut.
Click in textbox next to the "Press shortcuts:" label
Press "Control-H"
Click Assign  (Note assigned short cut does not appear in list)
Click Close

Press Control-H  
About window should appear.

Press Keyboard Shortcuts icon
Note no shortcut is displayed next to Help.About in list of commands.

![problem1](https://cloud.githubusercontent.com/assets/1952281/14397879/1d510ae4-fdae-11e5-87ac-e4ce883796a6.jpg)
![problem2](https://cloud.githubusercontent.com/assets/1952281/14397877/1d4bcdcc-fdae-11e5-820f-0d31af3b305a.jpg)
![problem3](https://cloud.githubusercontent.com/assets/1952281/14397878/1d4d099e-fdae-11e5-867e-eb7c1608ebb6.jpg)

**Comment by greg9504** [comment]
looking at the code it appears that the KeyboardMappingsCustomizationView uses the ICommandInfoService to fetch the command info, but registers changes to the ICommandManager.

The implementation of ICommandInfoService, CommandInfoService uses a "cache" of command info (_commandInfo = new Dictionary<string, ICommandInfo>(); )  
The cache is never updated.  Ultimately when a command isn't found CommandInfoService just goes to the CommandManager for the information.  

From my limited understanding the CommandInfoService doesn't seem to offer much benefit, at least to KeyboardMappingsCustomizationView which already references the CommandManager.

**Comment by GeertvanHorrik** [comment]
Good catch, will look into this, thanks for letting us know.

**Comment by GeertvanHorrik** [comment]
btw. you tried this on the latest develop branch / prerelease version of Orchestra?

**Comment by greg9504** [comment]
I downloaded the source as zip: 4/4/2016.

**Comment by GeertvanHorrik** [comment]
Fixed, thanks for reporting.
