### ISSUE TITLE
Release 2.3.0 to Nuget?

### ISSUE THREAD

**Issue by pm3378** [WildGums/Orchestra#47]
Could you please release  the v.2.3.0 to Nuget? It's only 2.2.0 available there, while there are breaking changes in Flyout there.

**Comment by Orcomp** [comment]
It is already released (was released on the 15th of December 2015). 

If you check Nuget Gallery: https://www.nuget.org/packages/Orchestra.Core/
And scroll down a little you will see it should be available.

Otherwise you can try downloading the pre-release 2.4.0-unstable0033 version
