### ISSUE TITLE
How to change language at runtime in a Orchestra-Application. 

### ISSUE THREAD

**Issue by Aitania** [WildGums/Orchestra#48]
I want to change language at runtime in a Orchestra-Application. 

But its only changes the language in BackstageTabItem which has the Focus. If i will restart the Application the selected language works fine!
I have two resource files. Resources.resx and Resources.de.resx

Is it possible to parse the whole XAML after language changed? (refresh)
Here a peace of XAML:

                    
                    <fluent:BackstageTabItem x:Name="Options"         
                      Header="{catel:LanguageBinding Options}"     <====== language changes at runtime!
                                             KeyTip="O">
                        <Grid Style="{DynamicResource InnerBackstageGridStyle}">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="50" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="*" />
                            </Grid.RowDefinitions>

                            
               <ContentControl Template="{StaticResource TitleRowAppNameAndImageDataTemplate}" />

                          <Label Grid.Row="1"
                    Content="{catel:LanguageBinding Options}"   <== language DON'T changes at runtime!
                                   FontFamily="Segoe UI Light"
                                   FontSize="40"
                                   Style="{DynamicResource RibbonBackstageHeaderLabelStyle}" />
                            <orchestra:RibbonBackstageTabControl Grid.Row="2">
                                
                                <orchestra:RibbonBackstageTabItem HeaderText="{catel:LanguageBinding General Options}"> <= language DON'T changes at runtime!

                                    <Grid>
                                        <Grid.RowDefinitions>
                                            <RowDefinition Height="Auto" />
                                            <RowDefinition Height="Auto" />
                                            <RowDefinition Height="Auto" />
                                        </Grid.RowDefinitions>
                                        <orchestra:RibbonBackstageTabItemHeader Grid.Row="0"
                                                 HeaderText="{catel:LanguageBinding General Options}"

                                                                                HeaderTextStyleKey="RibbonBackstageSubHeaderLabelStyleEx" />
                                        <Border Grid.Row="1"
                                                Height="1"
                                                Style="{StaticResource RibbonBorderStyle}"
                                                Visibility="{Binding PinnedItems,
                                                                     Converter={catel:CountCollapsedConverter}}" />
                                        <WrapPanel Grid.Row="2">
                                            <Grid>
                                                
                                                <GroupBox Grid.Row="2"
                                                          Height="111"
                                                          Header="{catel:LanguageBinding Language options}">
                                                    <Grid>
                                                        <Grid.ColumnDefinitions>
                                                            <ColumnDefinition Width="*" />
                                                            <ColumnDefinition Width="*" />
                                                            <ColumnDefinition Width="*" />
                                                        </Grid.ColumnDefinitions>

                                                        <Grid.RowDefinitions>
                                                            <RowDefinition Height="Auto" />
                                                            <RowDefinition Height="Auto" />
                                                            <RowDefinition Height="*" />
                                                        </Grid.RowDefinitions>

                                                        <Label Grid.Row="0"
                                                               Grid.Column="0"
                                                               Content="{catel:LanguageBinding Select the language}" />
                                                        <ComboBox Grid.Row="0"
                                                                  Grid.Column="1"
                                                                  DisplayMemberPath="Display"
                                                                  ItemsSource="{Binding AvailableLanguages}"
                                                                  SelectedItem="{Binding SelectedLanguage}" />

                                                        <TextBlock Grid.Row="0"
                                                                   Grid.Column="2"
                                                                   Margin="20,0,0,0"
                                                                   TextWrapping="Wrap">
                                                            <Run Text="{catel:LanguageBinding It is possible to switch the User interface language at runtime.}" />
                                                            <LineBreak />
  <Run Text="{catel:LanguageBinding The Application does not need to be restarted.}" />
 <Run Text="{catel:LanguageBinding It is possible to switch the User interface language.}" />
                                                            <LineBreak />
                                                            <LineBreak />
<Run Text="{catel:LanguageBinding Note that the changes will only take effect after you restart the Application.}" />
                                                        </TextBlock>
                                                    </Grid>
                                                </GroupBox>
                                            </Grid>

                                        </WrapPanel>
                                    </Grid>
                                </orchestra:RibbonBackstageTabItem>
                            </orchestra:RibbonBackstageTabControl>
                        </Grid>
                    </fluent:BackstageTabItem>
                    <!--  ============================================================  →

        //-----------------------------------------------------------------------------------------
        #region Methods     in     public class RibbonViewModel : ViewModelBase
        //-----------------------------------------------------------------------------------------
        private void OnSelectedLanguageChanged()
        {
            if (SelectedLanguage != null)
            {
                var newCulture = new CultureInfo(SelectedLanguage.Code);
                Thread.CurrentThread.CurrentUICulture =  #newCulture;
                _languageService.PreferredCulture = newCulture;

                MyProject.Properties.Settings.Default.DefaultLanguage = newCulture.Name;
                MyProject.Properties.Settings.Default.Save();
            }
        }
    
   //-----------------------------------------------------------------------------------------
     App : Application
    {
        protected override async void OnStartup(StartupEventArgs e)
{
            var languageService = ServiceLocator.Default.ResolveType<ILanguageService>();
            // languageService.PreferredCulture = new CultureInfo("de-DE");  
            // Read it the settings value... If not there "en-US"
            if (!string.IsNullOrEmpty(MyProject.Properties.Settings.Default.DefaultLanguage))
            {
                languageService.PreferredCulture = new CultureInfo(MyProject.Properties.Settings.Default.DefaultLanguage);
            }
            else
            {
                languageService.PreferredCulture = new CultureInfo("en-US");
            }
            languageService.FallbackCulture = new CultureInfo("en-US");

            // Create source for assembly MyApplication where the Resources.resx is located in the Properties folder

            var resourcesSource = new LanguageResourceSource("MyApplication", "MyProject.Properties", "Resources");

            languageService.RegisterLanguageSource(resourcesSource);

}

**Comment by GeertvanHorrik** [comment]
> But its only changes the language in BackstageTabItem which has the Focus

Interesting. The MarkUp extension in Catel should update at realtime (the focused one which you see), but also load the right ones when loading XAML (it uses the same service under the hood).

**Comment by Aitania** [comment]
I have solve this problem with WPFLocalizeExtension.
