### ISSUE TITLE
MetroDataWindow Enter Key  Close Missing

### ISSUE THREAD

**Issue by rrodriguez-consulting** [WildGums/Orchestra#51]
I think the CanCloseUsingEscape is good functionality , but for Enter key not is compactible,

We can implement CanCloseUsingEnter or CanExecuteDefaultCommandEnter   some controls as auto complete where the enter is basic handle to select a value, the windows is close to execute default command,
 it is the current code

```
 if (e.Key == System.Windows.Input.Key.Return)
      {
        if (this._defaultOkElement != null)
        {
          this._defaultOkElement.GotFocus += new RoutedEventHandler(this.OnButtonReceivedFocus);
          if (!this._defaultOkElement.Focus())
            this.HandleDefaultButton();
          e.Handled = true;
        }
        else if (this._defaultOkCommand != null)
        {
          this.HandleDefaultButton();
          e.Handled = true;
        }
      }
```

**Comment by GeertvanHorrik** [comment]
Hi @rramirez-nearsoft , this would probably need to be fixed in Catel or is this code found in Orchestra? I think it's a valid point to add this behavior to the DataWindow / Window. Are you interested in doing a PR?

**Comment by rrodriguez-consulting** [comment]
I did it in my app so let me do more testing to send this change to approve it
