### ISSUE TITLE
Missing style for a ListBox ?

### ISSUE THREAD

**Issue by ttustonic** [WildGums/Orchestra#52]
It seems that the style for a ListBox is missing or broken in the Fluent Ribbon Orchestra.
### Steps to reproduce
1. Put the following:
   `<SolidColorBrush x:Key="AccentColorBrush" Color="Magenta" />`
   in the generic.xaml file
2. Put this code:

```
            <TabItem Header="Aggregate">
                <ListBox Width="200" >
                    <ListBoxItem>Item 1</ListBoxItem>
                    <ListBoxItem>Item 2</ListBoxItem>
                    <ListBoxItem>Item 3</ListBoxItem>
                    <ListBoxItem>Item 4</ListBoxItem>
                    <ListBoxItem>Item 5</ListBoxItem>
                    <ListBoxItem>Item 6</ListBoxItem>
                    <ListBoxItem>Item 7</ListBoxItem>
                </ListBox>
            </TabItem>
```

in the MainView.xaml in Orchestra.Examples.Ribbon.Fluent.Shared
3.

Platform:
.NET version: 4.6
Windows 7 and Windows 8.1
### Expected behaviour

Selected and mouseover items should be magenta, like a File and View tabs in the screenshots
### Actual behaviour

On Windows 8 selected items are light blue colors. On Windows 7 there are no background colors for the selected and mouseover items

![orchestra examples ribbon_win7](https://cloud.githubusercontent.com/assets/5532089/19647488/98d3eb90-99fe-11e6-9cf8-a73b156fb74c.png)
![orchestra examples ribbon_win8](https://cloud.githubusercontent.com/assets/5532089/19647487/98d286c4-99fe-11e6-9ac2-7a1539d6fbdf.png)

**Comment by GeertvanHorrik** [comment]
Thanks for the detailed bug report. We will look into this.

**Comment by GeertvanHorrik** [comment]
![image](https://cloud.githubusercontent.com/assets/1246444/20831009/7254b7f8-b883-11e6-89d8-4cdd83c7cc62.png)

**Comment by GeertvanHorrik** [comment]
Done, we will release an unstable version of Orchestra today with this change. We expect to release a new stable release early January.
