### ISSUE TITLE
Add support for the question icon in the MessageService

### ISSUE THREAD

**Issue by GeertvanHorrik** [WildGums/Orchestra#53]
The MessageService has support for Information, Warning and Error. But the Question icon is not yet supported.

For the original thread, see https://catelproject.atlassian.net/browse/CTL-986.

**Comment by GeertvanHorrik** [comment]
Adding the message boxes to the Ribbon demo app:

![image](https://cloud.githubusercontent.com/assets/1246444/20829131/0efbc802-b87b-11e6-9be0-a73065122c4f.png)

**Comment by GeertvanHorrik** [comment]
Done. I've used some simple icons. If you want them nicer, feel free to improve via a PR :-)

**Comment by Aitania** [comment]
Wow! Thank you.

**Comment by Aitania** [comment]
Hallo Geert,
I have some not so "simple icons". I think the stop image must be something like a stop-hand, but the recording-stop goes at the moment.. *grins*
Could you please replace them in Controls.explicit.xaml...
I have left the SolidColorBrush like you have had it.
    
    <Geometry x:Key="StopGeometry">M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4M9,9V15H15V9</Geometry>
    <Geometry x:Key="ExclamationGeometry">M11,4.5H13V15.5H11V4.5M13,17.5V19.5H11V17.5H13Z</Geometry>
    <Geometry x:Key="ErrorGeometry">M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2C6.47,2 2,6.47 2,12C2,17.53 6.47,22 12,22C17.53,22 22,17.53 22,12C22,6.47 17.53,2 12,2M14.59,8L12,10.59L9.41,8L8,9.41L10.59,12L8,14.59L9.41,16L12,13.41L14.59,16L16,14.59L13.41,12L16,9.41L14.59,8Z</Geometry>
    <Geometry x:Key="WarningGeometry">M2,21.9997L12,2.00026L20.6247,19.2199L20.6291,19.2199L22,21.9997L22,21.9997L22,21.9997L2,21.9997ZM5.0287,19.9997L18.9638,19.9997L12,6.11526L5.0287,19.9997ZM12.9376,16.5456L11.2947,16.5456L11.2947,18.2081L12.9376,18.2081L12.9376,16.5456ZM12.9376,11.5581L11.2947,11.5581L11.2947,14.8831L12.9376,14.8831L12.9376,11.5581Z</Geometry>
    <Geometry x:Key="InfoGeometry">M11,9L13,9L13,7L11,7M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2C6.51416,2 2,6.51416 2,12C2,17.4858 6.51416,22 12,22C17.4858,22 22,17.4858 22,12C22,6.51416 17.4858,2 12,2M11,17L13,17L13,11L11,11L11,17Z</Geometry>
    
    <Geometry x:Key="QuestionGeometry">M11,18H13V16H11V18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,6A4,4 0 0,0 8,10H10A2,2 0 0,1 12,8A2,2 0 0,1 14,10C14,12 11,11.75 11,15H13C13,12.75 16,12.5 16,10A4,4 0 0,0 12,6Z</Geometry>
![question](https://cloud.githubusercontent.com/assets/4704114/20862033/129fd662-b9a0-11e6-8b37-4efc6179a925.PNG)
![stop](https://cloud.githubusercontent.com/assets/4704114/20862032/129e36d6-b9a0-11e6-8382-57db8132ad89.PNG)

**Comment by Aitania** [comment]
<Geometry x:Key="StopGeometry">M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4M9,9V15H15V9</Geometry>

    <Geometry x:Key="QuestionGeometry">M11,18H13V16H11V18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,6A4,4 0 0,0 8,10H10A2,2 0 0,1 12,8A2,2 0 0,1 14,10C14,12 11,11.75 11,15H13C13,12.75 16,12.5 16,10A4,4 0 0,0 12,6Z</Geometry>

**Comment by GeertvanHorrik** [comment]
@Aitania thanks for the PR, updated Orchestra. The only "ugly" one left is Exclamation, the rest looks good now.

**Comment by Aitania** [comment]
<Geometry x:Key="ExclamationGeometry">M11,15H13V17H11V15M11,7H13V13H11V7M12,2C6.47,2 2,6.5 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20Z</Geometry>

![exclamation](https://cloud.githubusercontent.com/assets/4704114/20925814/4b03a2e8-bbb9-11e6-8051-176f8e8c5d41.PNG)

The only "ugly" one left is Stop

**Comment by GeertvanHorrik** [comment]
Updated, thanks!
