### ISSUE TITLE
Missing geometry convertion in MahApps example

### ISSUE THREAD

**Issue by manne** [WildGums/Orchestra#58]
Flyout button does not show an arrow pointing to the right.

### Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/80180/21897611/71f4caf0-d8ea-11e6-8023-c9b57924b301.png)
1. Launch Mahapps example
2. Add a person

### Expected behaviour
Flyout button shows an arrow pointing to the right.
![image](https://cloud.githubusercontent.com/assets/80180/21897657/940d4fa4-d8ea-11e6-97a0-7c63bb3cda13.png)

### Actual behaviour
Flyout button does not show an arrow pointing to the right.

**PR is on its way**

**Comment by GeertvanHorrik** [comment]
Nice, this is how we love to get reports :-)
