### ISSUE TITLE
How to force a different culture for the whole application?

### ISSUE THREAD

**Issue by ttustonic** [WildGums/Orchestra#590]
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)

Hello

I have to force my whole application to use US culture, instead of Current culture.
Setting a `CurrentCulture ` and `CurrentUICulture` work for string conversions etc, but doesn't work for text boxes.
For example, in the image below _Mass tolerance_ and _Textbox double_ are bound to double values, and they have comma (Croatian format) instead of dot (required US format) as a decimal separator, while _Textbox string_ is correctly converted to have a decimal dot instead of comma.

The usual way to force culture:
`FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement) ..etc..`
doesn't work because it's already done in the Orchestra `ModuleInitializer`. Setting this in the App `OnStartup` or my `ModuleInitializer `generates an exception:
''Language' property was already registered by 'FrameworkElement'.'

So, is there another way to force different culture for UI elements, or a way to override or prevent Orchestra module initializer?

Thanks, Tom

![culture](https://user-images.githubusercontent.com/5532089/143486810-d9e61372-0832-40c2-9680-6627586dd47b.jpg)

**Comment by GeertvanHorrik** [comment]
This is a good point you raise. I think the way to fix this is to move the framework override from the module initializer to a point where the developer can actually interact (e.g. ApplicationInitializationService). Interested in doing a PR?

**Comment by ttustonic** [comment]
Hello
I'm not sure what would be the best way.
The minimal fix would be to just remove the line from the Module initializer, but perhaps you have something different in mind. Other changes would probably break `IApplicationInitializationService`.

**Comment by GeertvanHorrik** [comment]
I'll make a fix now. I'll indeed remove it from the module initializer.

**Comment by GeertvanHorrik** [comment]
See https://github.com/WildGums/Orchestra/commit/b23c5b02ab0ee0e13db35793a45afd2cd6f7df7e, releasing new alpha now.

**Comment by ttustonic** [comment]
Great!
Any chance of applying this fix to version 6.1 ? I'm, unfortunately, still stuck with .Net Framework :( and this is the last version which supports .Net 47... I'm planning to convert any day now, but there's always something more important.
Thanks, Tom

**Comment by ttustonic** [comment]
Ok.
Cannot test it now, but I guess it's OK. You can close this if you want.
Thanks, Tom
