### ISSUE TITLE
DotNetZip 1.15.0 in conflict with Catel.MVVM 5.12.22

### ISSUE THREAD

**Issue by lipchev** [WildGums/Orchestra#598]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?

DotNetZip 1.15.0 

## Version of Library

Orchestra.Core 6.6.6

## Steps to Reproduce
1. Install Orchestra.Shell.MahApps 6.6.6 (latest version)
2. Try to install Catel.MVVM 5.12.22 (latest version)
3. Observe: a conflict occurs between the package dependencies:

- Catel.MVVM 5.12.22 -> Catel.Core 5.12.22 -> System.Configuration.ConfigurationManager 6.0.0 -> System.Security.Permissions (>= 6.0.0) 
- Orchestra.Shell.MahApps 6.6.6 -> Orchestra.Core 6.6.6 -> DotNetZip 1.15.0 -> System.Security.Permissions (>= 5.0.0 && < 6.0.0)

## Expected Behavior

Since the release of DotNetZip 1.16.0 this should no longer be an issue : they have changed the constraint to `System.Security.Permissions (>= 4.7)`

## Actual Behavior

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We've removed DotNetZip from vNext in all our components and are using the internal components. We hope to release this early February.

For now explicitly install System.Securtiy.Permissions 6.0.0 to your project to bypass this issue.
