### ISSUE TITLE
Showing a custom dialog does not return the correct result in Mahapps

### ISSUE THREAD

**Issue by manne** [WildGums/Orchestra#61]
### Steps to reproduce

1. call `var dialogResult = await IUIVisualizerService.ShowDialogAsync<ExampleDialogOkCancelViewModel>();`. Whereas the corresponding view of `ExampleDialogOkCancelViewModel` is
```c#
    public partial class ExampleDialogOkCancelView : SimpleDataWindow
    {
        public ExampleDialogOkCancelView()
            : base(DataWindowMode.OkCancel)
        {
            InitializeComponent();
        }
    }
```
2. In the dialog click the Cancel button

### Expected behaviour
The value of `dialogResult` is `false`

Action | Result
------------ | -------------
Cancel | false
Ok | true
Apply | none, the dialog does not close
Close | null (??)

### Actual behaviour
calling `IUIVisualizerService.ShowDialogAsync` in Mahapps (implementation `MahAppsUIVisualizerService.ShowWindowAsync(FrameworkElement window, bool showModal)`) always returns `true` for a view of the type `CustomDialog`

@GeertvanHorrik can you review the content of the table, especially the result value of the close action. I will implement it and make a PR

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. The table looks exactly what it should be (yes, null for undecided close actions).
