### ISSUE TITLE
Managing the WindowState of Orchestra with FluentRibbon... Feuture request + Bug!

### ISSUE THREAD

**Issue by Aitania** [WildGums/Orchestra#63]
Hallo,
I am using Orchestra with FluentRibbon. I have asked some time ago
if it is possible to save the Size of the WindowShell.
[https://github.com/WildGums/Orchestra/issues/50#issuecomment-251909530](url)

I have notice that the behavior class RememberWindowSize works very gut!
Is it possiple to change the RibbonWindow to: 
<windows:RibbonWindow x:Class="Orchestra.Views.ShellWindow"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:orchestra="https://github.com/orcomp/orchestra"
                      xmlns:catel="http://catel.codeplex.com"
                      xmlns:windows="clr-namespace:Orchestra.Windows"
                      ShowInTaskbar="True" ResizeMode="CanResize"
                      _xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"_
                      Title="{Binding ElementName=ribbonContentControl, Path=Content.ViewModel.Title}">

    _<i:Interaction.Behaviors>
        <orchestra:RememberWindowSize />
    </i:Interaction.Behaviors>_

and remove the WindowState="Maximized" ?
There is an offset bug... I will look about it.

Regards,
Michael

**Comment by GeertvanHorrik** [comment]
We will look into this. *If* we implement it, we would probably do it via the shell service by adding additional properties so we don't break code for existing users.
