### ISSUE TITLE
MessageService's "No" button has Cancel's text, and "Cancel" button has no text

### ISSUE THREAD

**Issue by Kilazur** [WildGums/Orchestra#64]
### Steps to reproduce

1. Create a project using Orchestra & MahApps shell
2. Inject (I)MessageService in MainViewModel
3. Call MessageService.ShowAsync, and for the third parameter, select MessageButton.YesNo or MessageButton.YesNoCancel _(no issue with YesCancel)_
4. Launch the program

Platform:
.NET version: 4.0

### Expected behaviour

The "no" button should have the "no" text
The "cancel" button should have the "cancel" text

### Actual behaviour

The "no" has "cancel" text
The "cancel" button is blank (no text)

Examples:

var result = await MessageService.ShowAsync("", "", MessageButton.YesNo);
![orc_ma_err1](https://cloud.githubusercontent.com/assets/7058306/22151659/48fb0d5e-df1f-11e6-86f6-28d1ba0caa12.PNG)

var result = await MessageService.ShowAsync("", "", MessageButton.YesNoCancel);
![orc_ma_err2](https://cloud.githubusercontent.com/assets/7058306/22151664/5125b132-df1f-11e6-97e5-d329ce957f01.PNG)

**Comment by GeertvanHorrik** [comment]
This has been fixed recently. Please use the latest pre-release version of Orchestra.

**Comment by GeertvanHorrik** [comment]
Update: it's not fixed (yet), see PR #62
