### ISSUE TITLE
RecentItems and PinnedItems not visible in FluentRibbon demo

### ISSUE THREAD

**Issue by ttustonic** [WildGums/Orchestra#65]
### Steps to reproduce

1. Run one of Orchestra.Examples.Ribbon.Fluent

Platform:
.NET version: 4.5

### Expected behaviour
Recently used items and pinned items should be seen in the Ribbon Backstage.

### Actual behaviour
A list of recent and pinned shows no items, although items are added to PinnedItems and Items.
Visual Studio Output Window shows these messages:

System.Windows.Data Error: 40 : BindingExpression path error: 'PinnedItems' property not found on 'object' ''ShellViewModel' (HashCode=-1511088093)'. BindingExpression:Path=PinnedItems; DataItem='ShellViewModel' (HashCode=-1511088093); target element is 'ItemsControl' (Name=''); target property is 'ItemsSource' (type 'IEnumerable')

System.Windows.Data Error: 40 : BindingExpression path error: 'RecentlyUsedItems' property not found on 'object' ''ShellViewModel' (HashCode=-1511088093)'. BindingExpression:Path=RecentlyUsedItems; DataItem='ShellViewModel' (HashCode=-1511088093); target element is 'ItemsControl' (Name=''); target property is 'ItemsSource' (type 'IEnumerable')

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. Note that this feature is just an example, but we will fix it anyway.

**Comment by GeertvanHorrik** [comment]
@michu , can you fix this one?

**Comment by michu** [comment]
Fixed, https://github.com/WildGums/Orchestra/commit/f006efb79b93d26d8d63b648035d323a226ee182

**Comment by GeertvanHorrik** [comment]
Thanks for fixing, closing the issue.
