### ISSUE TITLE
ListBox crashes

### ISSUE THREAD

**Issue by ttustonic** [WildGums/Orchestra#66]
There are two related issues with ListBox in the Orchestra ver. 2.5. and the Fluent Ribbon shell.

*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Run Ribbon example. 
2. Open Aggregate tab and select an item in the ListBox, using mouse.
3. Alt-Tab from the example application 
or
4. Change an item using keyboard arrows.
5. Application crashes.

Platform: Windows 7
.NET version: 4.0, 4.6

### Expected behaviour

Tell us what should happen
It shouldn't crash :)
### Actual behaviour

Application crashes with the exception:

> System.InvalidOperationException was unhandled
Message: An unhandled exception of type 'System.InvalidOperationException' occurred in WindowsBase.dll
Additional information: '{DependencyProperty.UnsetValue}' is not a valid value for property 'FocusVisualStyle'.

The problem is in the Controls.listbox.xaml. Adding lines:
`<ResourceDictionary.MergedDictionaries>
 <ResourceDictionary Source="Controls.implicit.xaml" />
 </ResourceDictionary.MergedDictionaries>
`
seems to solve both issues.

HTH, Tom

**Comment by GeertvanHorrik** [comment]
@michu / @mkhomutov  who wants to pick this one as a hotfix?

**Comment by michu** [comment]
I will look into this one.

**Comment by michu** [comment]
Fixed in d6d64f1dda83fb276f0630940abd0eca2a01ad02, pushed commit into hotfix/2.5.1 branch.

**Comment by GeertvanHorrik** [comment]
@mkhomutov , can you please review + merge?

**Comment by mkhomutov** [comment]
sure, will do that today

**Comment by mkhomutov** [comment]
looks good. 
finishing hotfix
