### ISSUE TITLE
IdealForegroundColor is not White as expected.

### ISSUE THREAD

**Issue by samirem** [WildGums/Orchestra#67]
### Steps to reproduce

1. See the Orchestra.Examples.MahApps

### Expected behaviour

The IdealForegroundColor resource should be set to white (this is the default in MahApps).

### Actual behaviour

The IdealForegroundColor resource is set to black.

**Comment by GeertvanHorrik** [comment]
@michu can you fix this one?

**Comment by michu** [comment]
OK.

**Comment by michu** [comment]
Fixed in https://github.com/WildGums/Orchestra/commit/4a6b244c6f8786d1b7cd6fd393ac6189a144894d

**Comment by GeertvanHorrik** [comment]
Build - 2.6.0-unstable.13 should be available in about 5 minutes.
