### ISSUE TITLE
Fluent crashes with the Fluent Ribbon ver 5.0.1

### ISSUE THREAD

**Issue by ttustonic** [WildGums/Orchestra#68]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Upgrade Fluent.Ribbon Nuget package to 5.0.1
2. Run Orchestra.Examples.Ribbon.Fluent.NET46
3.

Platform:
.NET version: 4.6

### Actual behaviour

Application crashes in ThemeHelper, line 230. wth the XamlParseException, and inner exception message "Cannot locate resource 'themes/office2013/generic.xaml'."
The problem seems to be in the new Fluent ribbon which doesn't include office2013/generic.xaml.

**Comment by GeertvanHorrik** [comment]
Please test the latest pre-release of Orchestra. We already updated the develop branch to Fluent.Ribbon v5 :-)

**Comment by ttustonic** [comment]
Great, thanks
