### ISSUE TITLE
MessageDialog don't show on ActiveWindow (MahApps)

### ISSUE THREAD

**Issue by SebastienDegodez** [WildGums/Orchestra#71]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Open new child window ( type MetroDataWindow ) from ShellWindow
2. Call ShowAsync from MessageService
3. Look ! ;)

Platform: VisualStudio 2013
.NET version: 4.5.2

### Expected behaviour

The MessageBox is show on the shellWindow

### Actual behaviour
In "MahAppsMessageService" and "MahAppsUIVisualiserService"  use the ActiveWindow to display it on the correct right window.

I can contribute to fix it but I can't open the solution. What are the prerequisites ?
I have all *.Shared.csproj not loaded. (incompatible)

Thanks,

**Comment by GeertvanHorrik** [comment]
Thanks for reporting!

Shared projects need the Windows Templates to work (Windows Store apps).
