### ISSUE TITLE
Strange ModuleInitializer and Ribbon dependent behaviour

### ISSUE THREAD

**Issue by ArXen42** [WildGums/Orchestra#77]
### Steps to reproduce

Having the following `ModuleInitializer.cs` (with ModuleInit.Fody enabled):
```cs
public static class ModuleInitializer
{
	public static void Initialize()
	{
		IServiceLocator serviceLocator = ServiceLocator.Default;

		serviceLocator.RegisterType<IRibbonService, RibbonService>();
		serviceLocator.RegisterType<IApplicationInitializationService, ApplicationInitializationService>();
	}
}
```
everything works. However, when services registration is moved to the beginning of `App.xaml.cs`, the application hangs completely on showing the shell window. Stacktrace on pause and CPU load suggests that something related to measure/override UI elements sizes entered infinite loop.

My RibbonView has the following Ribbon definition:
```xaml
<fluent:Ribbon x:Name="Ribbon" IsQuickAccessToolBarVisible="False" CanCustomizeRibbon="False"
               AutomaticStateManagement="False"
               MaxHeight="98">
...
```

If the `MaxHeight` line is removed (used to crop groups headers that are unnecessary for me), application works again.

### Important note

It seems like the problem is caused not by removing _registration_ of the services from `ModuleInitializaer` but by removing `ServiceLocator.Default` call. So leaving just
```cs
public static class ModuleInitializer
{
	public static void Initialize()
	{
		IServiceLocator serviceLocator = ServiceLocator.Default;
	}
}
```
removes the problem.

**Platform**: WPF
**.NET version**: 4.7.1

### Expected behaviour

Ribbon visual layout not being affected by `ServiceLocator.Default` getter invocation place.

Created [log diff](https://gist.github.com/ArXen42/0c2b995d0b0345c36910a169e3dd37de) gist to show the differences between working and hanging app versions.

This is, of course, easily avoided problem, but such dependency is very strange and may cause unexpected problems somewhere else.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. I think Orchestra is trying to be smart and already taking care of the size for you. If you set the size on the MainView, see https://github.com/WildGums/Orchestra/blob/develop/src/Orchestra.Shell.Ribbon.Fluent/Views/ShellWindow.xaml.cs#L60

This way you don't actually need access to the window and can customize the min / max sizes from the main view directly.

**Comment by GeertvanHorrik** [comment]
If it only happens when customizing the height of the header for Fluent, it could also be related to Fluent.Ribbon instead of Orchestra.

**Comment by ArXen42** [comment]
What surprised me the most is that presence of that problem is dependent on whether the `ServiceLocator.Default` was invoked from ModuleInitializer before getting into `App.OnStartup`. I would expect Fluent.Ribbon control being either working with custom MaxHeight or completely broken in any case.

**Comment by ArXen42** [comment]
I initially got this issue on newly created project and another one that was used as template, but unable to reproduce on Orchestra.Examples.Fluent.Ribbon. Adding `LoadAssembliesOnStartup` to my project solves the problem as well as adding `ServiceLocator.Default` call to ModuleInitializer.

Seems like the problem is on my side (some differences in code, another project structure, usage of pre-release versions of all nuget packages except latest ControlzEx and Fluent.Ribbon).
