### ISSUE TITLE
I can't use orchestra FontImage with FontAwesome

### ISSUE THREAD

**Issue by MuhamadSelim** [WildGums/Orchestra#78]
I'm always getting InvalidOperationException: No glyph type face found

**Comment by GeertvanHorrik** [comment]
Please provide a repro because it's working in all our apps.

**Comment by MuhamadSelim** [comment]
Sorry , it was my fault I fixed it by 
`            FontImage.RegisterFont("FontAwesome", new FontFamily(new Uri("pack://application:,,,/Resources/Fonts/", UriKind.RelativeOrAbsolute), "./#FontAwesome"));
`
