### ISSUE TITLE
Severity Code Description Item File Line Prohibit display status in the demo project.

### ISSUE THREAD

**Issue by HinsHo** [WildGums/Orchestra#80]
I write the orchestra ribbon example follow the deom. but it show the error.

Severity Code Description Item File Line Prohibit display status in the demo project.

![error](https://user-images.githubusercontent.com/20653262/47660368-cdab3f00-dbd1-11e8-99de-5c20f3a24473.png)

**Comment by HinsHo** [comment]
![image](https://user-images.githubusercontent.com/20653262/47660980-20d1c180-dbd3-11e8-8c1a-763b0dcd288d.png)

**Comment by GeertvanHorrik** [comment]
What is the version of Fluent.Ribbon you are using? Are you maybe using a newer version?

**Comment by HinsHo** [comment]
The version of Fluent.Ribbon is 6.1.0.233

**Comment by GeertvanHorrik** [comment]
We can't seem to reproduce :(

**Comment by HinsHo** [comment]
I try to update the Fluent.Ribbon version. but  it can not work. I don't known why.

[Orchestra.Examples.Ribbon.Fluent.zip](https://github.com/WildGums/Orchestra/files/2539149/Orchestra.Examples.Ribbon.Fluent.zip)
