### ISSUE TITLE
How to disable Orchestra.DotNetPatchHelper?

### ISSUE THREAD

**Issue by Drachenkaetzchen** [WildGums/Orchestra#91]
I use an own `UnhandledExceptionHandler` so I don't need `Orchestra.DotNetPatchHelper`. From looking at the code, there doesn't seem to be an easy way, as it is always called, even during `ModuleInit`.

I guess this is more a feature request instead of a question ;)

**Comment by GeertvanHorrik** [comment]
Good question. I think we need to allow for some sort of handler registration (where this one is enabled by default), but can be removed. Need to think about how I can introduce this without breaking changes.

**Comment by Drachenkaetzchen** [comment]
Well I have thought about this for a bit and to me it seems the easiest solution would be to add a deinitialize function to DotNetPatchHelper:

```
public static void Deinitialize()
        {
            var appDomain = AppDomain.CurrentDomain;
            appDomain.UnhandledException -= OnAppDomainUnhandledException;
            appDomain.FirstChanceException -= OnAppDomainFirstChanceException;
            application.DispatcherUnhandledException -= OnDispatcherUnhandledException;
        }
```

That way, the developer using Orchestra can decide when not to use the DotNetPatchHelper.

In my case, it would be both for production and development, as for release I'm using an own handler for `DispatcherUnhandledException`, but other developers might want to disable this functionality only when debugging.

**Comment by GeertvanHorrik** [comment]
Yeah, let's call it Uninitialize (or maybe attach / detach) and it could work!

**Comment by Drachenkaetzchen** [comment]
Sounds good to me! I wanted to create a PR, but I have trouble getting Orchestra to build. It probably has something to do with the multi-targeting, but I lost track of the many different error messages I've got during my trials and I really don't want to send a PR without having it tested previously :(

**Comment by GeertvanHorrik** [comment]
Yeah, we are sort of in-between (because of prereleases of .net core 3.0 where we want to be prepared for). Will look into this myself.

**Comment by GeertvanHorrik** [comment]
Introducing DotNetPatchHelper.Attach & Detach

**Comment by GeertvanHorrik** [comment]
Done, thanks for reporting.
