### ISSUE TITLE
Orchestra.Tests fails

### ISSUE THREAD

**Issue by IvanGit** [WildGums/Orchestra#951]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [+ ] WPF
 - [ ] Blazor WASM
 - [ ] .NET Core

## Component

What component is this issue occurring in?
[Orchestra](https://github.com/WildGums/Orchestra)

## Version of Library

Latest

## Version of OS(s) listed above with issue

Win 10

## Steps to Reproduce
1. Clone repo
2. Build
3. Run tests

## Expected Behavior

All tests passed

## Actual Behavior

Tests failed.

![image](https://github.com/user-attachments/assets/e2c8367f-d522-4e81-b5e5-f1feffdd6dce)

**Comment by GeertvanHorrik** [comment]
Great that you add this here. If you install BeyondCompare (we really like this tool for diff viewing), you will automatically see why it fails. Probably you are running the tests in debug mode where WPF sometimes add "XamlGeneratedNamespace" to the end.

This makes me think, maybe we can disable / trim the XamlGeneratedNamespace? What do you think @ceo1647 ? It's something that should be applied to all libs if we go for this.

**Comment by IvanGit** [comment]
Yes, XamlGeneratedNamespace is a reason.

**Comment by GeertvanHorrik** [comment]
See https://github.com/PublicApiGenerator/PublicApiGenerator/issues/395

Will close this ticket for now.
